<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Tiferet.Avalonia.Examples.Calculator</AssemblyName>
    <RootNamespace>Tiferet.Avalonia.Examples.Calculator</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Tiferet.Avalonia\Tiferet.Avalonia.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Tiferet" Version="1.0.0-beta.7" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="app\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.2.7" />
    <PackageReference Include="Avalonia.Desktop" Version="11.2.7" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.2.7" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.2.7" />
  </ItemGroup>

</Project>
